### PR TITLE
Fix `MediaCalendar` crash by marking it `@MainActor`

### PR DESCRIPTION
**Pull request by pteasima**
There's not much to test here, it still builds with this one line change and in theory should help.

Again, I recommend we do these things throughout the codebase as one larger refactoring task.

### CODE REVIEW

**Review by tillkruss — COMMENTED** [review]
Does it make sense to make flag most models as `@MainActor`?

**Comment by pteasima** [comment]
> Does it make sense to make flag most models as `@MainActor`?

I think so. Here's my iMessage from today on this very topic: "This one probably has quite an easy fix [...], but it also reveals a larger issue where maybe we just never synchronized anything we might wanna just mark anything we touch from views as `@MainActor`. Im making you aware since this would be a larger refactoring effort after which we may want to reassess and see whether many crashes are gone."

So all models and also most or all view methods (afaik we can't quite mark the whole views as mainactor, because hasn't properly some things like `@Environment` so it won't let you. But most view-related things should indeed be `@MainActor`. I never fully got into the habit of doing this because most my codebases use a lot of `@State` and very few `@Observable`, but in Ruddarr I'd do it as much as possible. If in some case its not possible, at least it surfaces a potential issue.

**Comment by pteasima** [comment]
But I should probably make it clear that some of the logic is ok to run off the main thread. So in theory its just the properties and not all the methods. But i'd recommend to just play it safe, mark the type `@MainActor` and solve any performance issues that arise (very few or none at all) by `nonisolated`

**Comment by tillkruss** [comment]
So all the models do HTTP requests, as long as we can mark the model as main actor without the HTTP requests blocking the entire UI we're good.

**Pull request merged**
